<?php

/**
 * Implements hook_ctools_plugin_api().
 */
function panels_ajax_tab_ctools_plugin_api() {
  return array("version" => "1");
}

/**
 * Implementation of hook_ctools_plugin_dierctory() to let the system know
 * we implement plugins.
 */
function panels_ajax_tab_ctools_plugin_directory($module, $plugin) {
  if ($plugin == 'content_types') {
    return 'plugins/' . $plugin;
  }
}

/**
 * Implementation of hook_menu()
 */
function panels_ajax_tab_menu() {
  $items = array();

  $items['panels_ajax_tab/%/%'] = array(
    'title' => 'panels-ajax tab AJAX callback',
    'description' => 'AHAJ callback for panels tabs',
    'page callback' => 'panels_ajax_tab_ajax',
    'page arguments' => array(1,2),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * AHAH call-back for preview
 */
function panels_ajax_tab_ajax($panel_name, $context_string) {
  ctools_include('context');
  ctools_include('plugins', 'panels');

  $mini = panels_mini_load($panel_name);

  if ($context_string != 'none') {
    $parts = explode(':', $context_string);
    $entity_type = strtolower($parts[0]);
    $entity_id = (int) $parts[1];
    $entity = array_pop(entity_load($entity_type, array($entity_id)));

    // If it's a node, check node-view permissions
    if ($entity_type == 'node') {
      if (!node_access('view', $entity)) {
        drupal_access_denied();
        exit();
      }
    }

    $context_plugin = ctools_get_plugins('ctools', 'contexts', 'entity');
    $context_plugin['keyword'] = $entity_type;
    $context = ctools_context_create_entity(FALSE, $entity, FALSE, $context_plugin);

    // Load up any contexts we might be using.
    $context = ctools_context_match_required_contexts($mini->requiredcontexts, array($context));
    $mini->context = $mini->display->context = ctools_context_load_contexts($mini, FALSE, $context);
  }

  if (empty($mini) || !empty($mini->disabled)) {
    return;
  }

  $mini->display->args = $panel_args;
  $mini->display->css_id = panels_mini_get_id($subtype);
  $mini->display->owner = $mini;
  // unique ID of this mini.
  $mini->display->owner->id = $mini->name;

  // Clear the JavaScript and CSS that are not related to the panels being rendered - they already exists
  drupal_static_reset('drupal_add_js');
  drupal_static_reset('drupal_add_css');

  $output = panels_render_display($mini->display);

  // Done generating output, let's print it
  print '<?xml version="1.0" encoding="UTF-8" ?>';
  print '
    <html version="HTML+RDFa+MathML 1.1"
    xmlns:content="http://purl.org/rss/1.0/modules/content/"
    xmlns:dc="http://purl.org/dc/terms/"
    xmlns:foaf="http://xmlns.com/foaf/0.1/"
    xmlns:og="http://ogp.me/ns#"
    xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"
    xmlns:sioc="http://rdfs.org/sioc/ns#"
    xmlns:sioct="http://rdfs.org/sioc/types#"
    xmlns:skos="http://www.w3.org/2004/02/skos/core#"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema#"
    xmlns:mml="http://www.w3.org/1998/Math/MathML">
  ';
  print '<head>';
  print drupal_get_js();
  print drupal_get_css();
  $layout = panels_get_layout($mini->display->layout);
  print "<link rel='stylesheet' type='text/css' href='".base_path().$layout['path'].'/'.$layout['css']."' />";
  print '</head>';
  print '<body>';
  print $output;
  print '</body></html>';
  exit;
}
