<?php

/**
 * Implements hook_ctools_plugin_api().
 */
function panels_ajax_tab_ctools_plugin_api() {
  return array("version" => "1");
}

/**
 * Implementation of hook_ctools_plugin_dierctory() to let the system know
 * we implement plugins.
 */
function panels_ajax_tab_ctools_plugin_directory($module, $plugin) {
  if ($plugin == 'content_types') {
    return 'plugins/' . $plugin;
  }
}

/**
 * Implementation of hook_menu()
 */
function panels_ajax_tab_menu() {
  $items = array();

  $items['panels_ajax_tab/%/%'] = array(
    'title' => 'panels-ajax tab AJAX callback',
    'description' => 'AHAJ callback for panels tabs',
    'page callback' => 'panels_ajax_tab_ajax',
    'page arguments' => array(1,2),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implementation of hook_menu()
 */
function panels_ajax_tab_theme($existing, $type, $theme, $path) {
  return array(
    'panels_ajax_tab_tabs' => array(
      'variables' => array('minipanels' => NULL, 'tab_container_id' => NULL, 'context_string' => NULL),
    ),
    'panels_ajax_tab_container' => array(
      'variables' => array('minipanels' => NULL, 'tab_container_id' => NULL, 'context_string' => NULL),
    ),
    'panels_ajax_tab_ajax' => array(
      'variables' => array('minipanel' => NULL),
    ),
  );
}

/**
 * AHAH call-back for preview
 */
function panels_ajax_tab_ajax($panel_name, $context_string) {
  ctools_include('context');
  ctools_include('plugins', 'panels');

  $mini = panels_mini_load($panel_name);

  if ($context_string != 'none') {
    $parts = explode(':', $context_string);
    $entity_type = strtolower($parts[0]);
    $entity_id = (int) $parts[1];
    $entity = array_pop(entity_load($entity_type, array($entity_id)));

    // If it's a node, check node-view permissions
    if ($entity_type == 'node') {
      if (!node_access('view', $entity)) {
        drupal_access_denied();
        exit();
      }
    }

    $context_plugin = ctools_get_plugins('ctools', 'contexts', 'entity');
    $context_plugin['keyword'] = $entity_type;
    $context = ctools_context_create_entity(FALSE, $entity, FALSE, $context_plugin);

    // Load up any contexts we might be using.
    $context = ctools_context_match_required_contexts($mini->requiredcontexts, array($context));
    $mini->context = $mini->display->context = ctools_context_load_contexts($mini, FALSE, $context);
  }

  if (empty($mini) || !empty($mini->disabled)) {
    return;
  }

  $mini->display->owner = $mini;
  // unique ID of this mini.
  $mini->display->owner->id = $mini->name;

  // Clear the JavaScript and CSS that are not related to the panels being rendered - they already exists
  drupal_static_reset('drupal_add_js');
  drupal_static_reset('drupal_add_css');

  print theme('panels_ajax_tab_ajax', array('minipanel' => $mini));

  exit;
}


function theme_panels_ajax_tab_tabs($vars) {
  foreach ($vars['minipanels'] as $mini) {
    $tabs[] = '<a href="#" class="panels-ajax-tab-tab" data-panel-name="'.$mini->name.'" data-target-id="' . $vars['tab_container_id'] . '" data-entity-context="' . $vars['context_string'] . '">' . $mini->admin_title . '</a>';
  }
  return theme('item_list', array('items' => $tabs, 'attributes' => array('class' => array('tabs', 'inline', 'panels-ajax-tab'))));
}

function theme_panels_ajax_tab_container($vars) {
  return '<div id="panels-ajax-tab-container-' . $vars['tab_container_id'] . '" class="panels-ajax-tab-container"></div>';
}

function theme_panels_ajax_tab_ajax($vars) {
  $mini = $vars['minipanel'];
  $layout = panels_get_layout($mini->display->layout);
  $panels_output = panels_render_display($mini->display);

  $output  = '';
  $output .= '<?xml version="1.0" encoding="UTF-8" ?>';
  $output .= '
    <html version="HTML+RDFa+MathML 1.1"
    xmlns:content="http://purl.org/rss/1.0/modules/content/"
    xmlns:dc="http://purl.org/dc/terms/"
    xmlns:foaf="http://xmlns.com/foaf/0.1/"
    xmlns:og="http://ogp.me/ns#"
    xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"
    xmlns:sioc="http://rdfs.org/sioc/ns#"
    xmlns:sioct="http://rdfs.org/sioc/types#"
    xmlns:skos="http://www.w3.org/2004/02/skos/core#"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema#"
    xmlns:mml="http://www.w3.org/1998/Math/MathML">
  ';
  $output .= '<head>';
  $output .= drupal_get_js();
  $output .= drupal_get_css();

  $output .= "<link rel='stylesheet' type='text/css' href='".base_path().$layout['path'].'/'.$layout['css']."' />";
  $output .= '</head>';
  $output .= '<body>';
  $output .= $panels_output;
  $output .= '</body></html>';
  return $output;
}
